# Generated by Django 5.2.17 on 2026-09-12 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciler', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systemarecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='systembentry',
            name='raw_value',
        ),
        migrations.AddField(
            model_name='systemarecord',
            name='actor_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='systemarecord',
            name='adjustment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='systemarecord',
            name='base_value',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='systemarecord',
            name='category_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemarecord',
            name='event_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemarecord',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemarecord',
            name='total_value',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='systembentry',
            name='entry_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='systembentry',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='systembentry',
            name='recorded_on',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systembentry',
            name='value',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='external_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='reconciler.organization'),
        ),
        migrations.AlterField(
            model_name='systemarecord',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reconciler.location'),
        ),
        migrations.AlterField(
            model_name='systemarecord',
            name='row_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='systembentry',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reconciler.location'),
        ),
        migrations.AlterField(
            model_name='systembentry',
            name='record_ref',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='systembentry',
            name='row_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('external_id', 'organization')},
        ),
        migrations.RemoveField(
            model_name='systemarecord',
            name='raw_value',
        ),
    ]
